## Matrices

Las matrices se crean con el operador **`matrix()`**

In [1]:
v <- 11:20
v

[1] 11 12 13 14 15 16 17 18 19 20

In [2]:
A <- matrix(v)
A

[,1]
 [1,] 11  
 [2,] 12  
 [3,] 13  
 [4,] 14  
 [5,] 15  
 [6,] 16  
 [7,] 17  
 [8,] 18  
 [9,] 19  
[10,] 20

Notemos que por default las matrices se crean siguiendo un orden vertical, ie. por columnas

In [3]:
A <- matrix(v, nrow =2)
A

[,1] [,2] [,3] [,4] [,5]
[1,] 11   13   15   17   19  
[2,] 12   14   16   18   20

In [4]:
A <- matrix(v, nrow =2, byrow=T)
A

[,1] [,2] [,3] [,4] [,5]
[1,] 11   12   13   14   15  
[2,] 16   17   18   19   20

In [5]:
col1 <- c(100,200,300)
col2 <- c(500,700,900)

c(col1,col2)

[1] 100 200 300 500 700 900

In [6]:
B <- matrix( c(col1,col2) , nrow =2, byrow = TRUE)
B

[,1] [,2] [,3]
[1,] 100  200  300 
[2,] 500  700  900

In [7]:
col_names <- c('Ene','Feb','Mar')

colnames(B) <- col_names

B

Ene Feb Mar
[1,] 100 200 300
[2,] 500 700 900

In [8]:
row_names <- c('Empresa1','Empresa2')

rownames(B) <- row_names

B

Ene Feb Mar
Empresa1 100 200 300
Empresa2 500 700 900

## Operaciones aritméticas con matrices

In [9]:
v <- (1:40)
v

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40

In [10]:
A <- matrix(v , nrow = 4)
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    5     9   13   17   21   25   29   33   37   
[2,] 2    6    10   14   18   22   26   30   34   38   
[3,] 3    7    11   15   19   23   27   31   35   39   
[4,] 4    8    12   16   20   24   28   32   36   40

In [11]:
A <- matrix(v, nrow = 4, byrow = TRUE)
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40

In [12]:
A + 5

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  6    7    8    9   10   11   12   13   14   15   
[2,] 16   17   18   19   20   21   22   23   24   25   
[3,] 26   27   28   29   30   31   32   33   34   35   
[4,] 36   37   38   39   40   41   42   43   44   45

In [13]:
A*2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18   20   
[2,] 22   24   26   28   30   32   34   36   38   40   
[3,] 42   44   46   48   50   52   54   56   58   60   
[4,] 62   64   66   68   70   72   74   76   78   80

In [14]:
A/2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5  1    1.5  2    2.5  3    3.5  4    4.5  5   
[2,]  5.5  6    6.5  7    7.5  8    8.5  9    9.5 10   
[3,] 10.5 11   11.5 12   12.5 13   13.5 14   14.5 15   
[4,] 15.5 16   16.5 17   17.5 18   18.5 19   19.5 20

In [15]:
A^2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]   1     4    9   16   25   36   49   64   81  100 
[2,] 121   144  169  196  225  256  289  324  361  400 
[3,] 441   484  529  576  625  676  729  784  841  900 
[4,] 961  1024 1089 1156 1225 1296 1369 1444 1521 1600

In [16]:
B <- A*A
B

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]   1     4    9   16   25   36   49   64   81  100 
[2,] 121   144  169  196  225  256  289  324  361  400 
[3,] 441   484  529  576  625  676  729  784  841  900 
[4,] 961  1024 1089 1156 1225 1296 1369 1444 1521 1600

In [17]:
filtro <- (B > 500)
filtro

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [18]:
B[filtro]

[1]  961 1024  529 1089  576 1156  625 1225  676 1296  729 1369  784 1444  841
[16] 1521  900 1600

### Operaciones con respecto a filas o columnas

In [19]:
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40

In [20]:
# Suma de cada columna:
colSums(A)

[1]  64  68  72  76  80  84  88  92  96 100

In [21]:
colMeans(A)

[1] 16 17 18 19 20 21 22 23 24 25

In [22]:
# Suma de cada renglón:
rowSums(A)

[1]  55 155 255 355

### Acceso a la entradas de una matriz

In [23]:
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40

In [24]:
A[3,1]

[1] 21

In [25]:
# Acceso a los valores de un reglón:
A[2,]

[1] 11 12 13 14 15 16 17 18 19 20

In [26]:
# Acceso a los valores de varos reglones:
A[3:4,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 21   22   23   24   25   26   27   28   29   30   
[2,] 31   32   33   34   35   36   37   38   39   40

In [27]:
# Acceso a los valores de una columna:
A[,2]

[1]  2 12 22 32

In [28]:
# Acceso a los valores de varias columnas:
A[,3:6]

[,1] [,2] [,3] [,4]
[1,]  3    4    5    6  
[2,] 13   14   15   16  
[3,] 23   24   25   26  
[4,] 33   34   35   36

In [29]:
# Submatrices
A[2:3, 8:9]

[,1] [,2]
[1,] 18   19  
[2,] 28   29

In [30]:
# Media de la columna 3:
colMeans(A)[3]

[1] 18

In [31]:
# Media de la columna 3:
sum(A[,3])/length(A[,3])

[1] 18

### Agregar renglones a una matriz

In [32]:
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40

In [33]:
new_row <- colSums(A)
new_row

[1]  64  68  72  76  80  84  88  92  96 100

In [34]:
A <- rbind(A, new_row)
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
         1    2    3    4    5    6    7    8    9    10  
        11   12   13   14   15   16   17   18   19    20  
        21   22   23   24   25   26   27   28   29    30  
        31   32   33   34   35   36   37   38   39    40  
new_row 64   68   72   76   80   84   88   92   96   100

### Agregar columnas a una matriz

In [35]:
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
         1    2    3    4    5    6    7    8    9    10  
        11   12   13   14   15   16   17   18   19    20  
        21   22   23   24   25   26   27   28   29    30  
        31   32   33   34   35   36   37   38   39    40  
new_row 64   68   72   76   80   84   88   92   96   100

In [36]:
new_col <- rowMeans(A)
new_col

new_row 
    5.5    15.5    25.5    35.5    82.0

In [37]:
A <- cbind(A, new_col)
A

new_col
         1  2  3  4  5  6  7  8  9  10  5.5   
        11 12 13 14 15 16 17 18 19  20 15.5   
        21 22 23 24 25 26 27 28 29  30 25.5   
        31 32 33 34 35 36 37 38 39  40 35.5   
new_row 64 68 72 76 80 84 88 92 96 100 82.0